### ISSUE TITLE
Storing RuCoLa on HuggingFace

### ISSUE THREAD

**Issue by NathanGodey** [RussianNLP/RuCoLA#2]
Hello,
Thanks for this cool work! I'd like to be able to use the HF datasets environment, and thus I was wondering if you would agree to let me put this dataset on the HuggingFace Hub as is?

**Comment by vmkhlv** [comment]
Hi, thank you for your contributions. We've released RuCoLA on HF: https://huggingface.co/datasets/RussianNLP/rucola
