### ISSUE TITLE
Inference on ruRoBERTa-large-rucola

### ISSUE THREAD

**Issue by AleksandrIvchenko** [RussianNLP/RuCoLA#3]
Would you be so kind as to provite an example on inference?

Cause there are no info on hugging face here https://huggingface.co/RussianNLP/ruRoBERTa-large-rucola/blob/main/README.md

**Comment by vmkhlv** [comment]
hey, sorry for such a long response :)

you can follow inference examples provided on the huggingface page: https://huggingface.co/RussianNLP/ruRoBERTa-large-rucola?library=transformers
